version: '3'

services:
  db:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: postgres:9.6-alpine
    ports:
      - "5434:5432"
  web:
    image: rust-team-project:latest
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5434/${POSTGRES_DB}"
    depends_on:
      - db
    network_mode: host
