version: '3'

services:
  rabbitmq:
        image: rabbitmq:3-management
        volumes:
            - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/defu.json
            - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
            - ./rabbitmq/logs:/var/log/rabbitmq/log
        ports:
            - 5672:5672
            - "127.0.0.1:15672:15672"
  db:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    image: "postgres:12"
    ports:
      - "5433:5432"
  web:
    restart: unless-stopped
    image: rust-team-project:latest
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      #i have  no clu why but we need to use 5432
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      - db
      - rabbitmq
