// Generated by diesel_ext

use diesel::Queryable;

#[derive(Queryable, Debug, Clone)]
pub struct Todo {
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub visibility: i16,
}

